parameters:
#    merci_cart.example.class: Merci\CartBundle\Example

services:
#    merci_cart.example:
#        class: %merci_cart.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
